return {
    ['Sign'] = {
        Price = 150,
        Description = 'A sign that you can write on.',
        Image = 'rbxassetid://1234567890'
    },
    ['Radio'] = {
        Price = 200,
        Description = 'A radio that plays music.',
        Image = 'rbxassetid://1234567890'
    },
    ['SpeedCoil'] = {
        Price = 150,
        Description = 'A coil that makes you run faster.',
        Image = 'rbxassetid://1234567890'
    },
    ['JumpCoil'] = {
        Price = 150,
        Description = 'A coil that makes you jump higher.',
        Image = 'rbxassetid://1234567890'
    },
    ['Bike'] = {
        Price = 500,
        Description = 'A bike that you can ride.',
        Image = 'rbxassetid://1234567890'
    },
    ['SkateBoard'] = {
        Price = 300,
        Description = 'A skateboard that you can ride.',
        Image = 'rbxassetid://1234567890'
    },
    ['Pistol'] = {
        Price = 4999,
        Description = 'A pistol that you can shoot.',
        Image = 'rbxassetid://1234567890'
    };
} :: {
    [string]: {
        Price: number,
        Description: string,
        Image: string
    };
};