return {
    ['Sign'] = {
        Price = 150,
        Description = 'A sign that you can write on.',
        Image = 'rbxassetid://18455096518'
    },
    ['Boombox'] = {
        Price = 200,
        Description = 'A radio that plays music.',
        Image = 'rbxassetid://18455142066'
    },
    ['SpeedCoil'] = {
        Price = 150,
        Description = 'A coil that makes you run faster.',
        Image = 'rbxassetid://18451682497'
    },
    ['JumpCoil'] = {
        Price = 150,
        Description = 'A coil that makes you jump higher.',
        Image = 'rbxassetid://18451636034'
    },
    ['Bike'] = {
        Price = 500,
        Description = 'A bike that you can ride.',
        Image = 'rbxassetid://18454993912'
    },
    ['SkateBoard'] = {
        Price = 300,
        Description = 'A skateboard that you can ride.',
        Image = 'rbxassetid://18451739943'
    },
    ['Gun'] = {
        Price = 4999,
        Description = 'A gun that you can shoot.',
        Image = 'rbxassetid://18455719399'
    }
} :: {
    [string]: {
        Price: number,
        Description: string,
        Image: string
    };
};